api_key: YOUR_HOLOPIN_API_KEY
issuers:
  - "@user:matrix.org"
badges:
  hackathon2022:
    type: "regular"
    id: "cldbf3qbm1169608l9mo7y9o8u"
    description: |
      This badge was issued by using the Maubot Holopin plugin.
    earning_criteria: |
      To earn this badge, you must develop an integration for the [Matrix] communication network.
